<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the Closure to execute when that URI is requested.
|
*/

Route::get('laravel-version', function()
{
$laravel = app();
return "Your Laravel version is ".$laravel::VERSION;
});

Route::get('/', function(){
	return View::make('template.framework_datatable_base');
});

// !! BEGIN TESTING !!
Route::get('/test', function(){
	NewsPost::withTrashed()->find(2)->restore();
});


/*
Route::get('/{js', function(){
	return View::make('template.framework_datatable_base');
});
*/


//Route::get('users', array('uses' => 'UsersController@index'));

//Route::get('users', 'UsersController@show_datatable');

// Route::get('/pagescontroller', 'PagesController@home');

// Route::get('/allusers', function() {
	// $users = User::all();
	// return View::make('users/index')->with('users', $users);
// });

// Route::get('/adduser', function() {

	// $mod = User::create([
		// 'F_CREATE_KEY' => 'FKFlllll',
		// 'USERNAME' => 'wtf',
		// 'HASH' => Hash::make('passwordtxt'),
		
		// 'F_CREATED_BY' => '4',
		// 'F_UPDATED_BY' => '4'
	// ]);
	
	// dd($mod);
	
	// return User::all();
// });

// Route::get('/deluser', function() {

	// User::where('MK', '=', '12')->restore();
	
	// return User::all();
// });


// debug: print sql stmt when sql is generated by orm
DB::listen(function($sql, $bindings, $time)
{
	//echo "<script>alert('" .$sql. "');</script>";
});



// Users legacy
/*
Route::patch('/users/bulk', ['as' => 'users.bulk' , 'uses' => 'UsersController@bulk']);
//Route::get('/users/populate', ['as' => 'users.populateView' , 'uses' => 'UsersController@populateDatatable']);
Route::resource('users', 'UsersController');
*/



Route::get('/area51', function(){
	return View::make('template.login');
});
Route::post('/area51/login', ['as' => 'adminauth.login' , 'uses' => 'AdminAuthController@login']);
//Route::resource('adminauth', 'AdminAuthController');
//Route::get('/admin/login', 'AdminAuthController');

// Wizard
Route::get('/wizard', function(){
	return View::make('template.framework_wizard');
});

// Database schema controller
Route::get('/dbschema/tables', ['as' => 'dbtables.tableNames' , 'uses' => 'DatabaseSchemaController@getTableNames']);
Route::get('/dbschema/tables/{tableName}', ['as' => 'dbtables.tableColumns' , 'uses' => 'DatabaseSchemaController@getTableColumnNames']);


// Model Management
Route::post('/models/{modelName}', ['as' => 'models.store' , 'uses' => 'ModelManagementController@createModel']);

// Controller Management
Route::post('/controllers/{controllerName}', ['as' => 'controllers.store' , 'uses' => 'ControllerManagementController@createController']);

// DatatableView Management
Route::post('/dtviews/{datatableViewFolderName}', ['as' => 'dtviews.store' , 'uses' => 'DatatableViewManagementController@createDatatableView']);

//Route::controller('/users', 'UsersController', ['bulk' => 'bulk']);

/*
Route::group(null, function() {
Route::resource('users', 'UsersController');
//Route::get('/users/bulk', 'UsersController@bulk');
Route::controller('/users', 'UsersController', ['bulk' => 'bulk']);

});
*/
Route::patch('/dtnewsposts/bulk', ['as' => 'dtnewsposts.bulk' , 'uses' => 'DTNewsPostController@bulk']);
Route::resource('dtnewsposts', 'DTNewsPostController');

Route::get('/dtusers/query', ['as' => 'dtusers.query' , 'uses' => 'DTRegisteredUserController@query']);
Route::patch('/dtusers/bulk', ['as' => 'dtusers.bulk' , 'uses' => 'DTRegisteredUserController@bulk']);
Route::resource('dtusers', 'DTRegisteredUserController');

//Route::get('/dtprivilegedusers/query', ['as' => 'dtprivilegedusers.query' , 'uses' => 'DTPrivilegedUserController@query']);
Route::patch('/dtprivilegedusers/bulk', ['as' => 'dtprivilegedusers.bulk' , 'uses' => 'DTPrivilegedUserController@bulk']);
Route::resource('dtprivilegedusers', 'DTPrivilegedUserController');

Route::post('/cnewsposts/favourite/{id}', ['as' => 'cnewsposts.fav' , 'uses' => 'CNewsPostController@addFavourite']);
Route::post('/cnewsposts/unfavourite/{id}', ['as' => 'cnewsposts.unfav' , 'uses' => 'CNewsPostController@removeFavourite']);


Route::post('/cnewsposts/report/{id}', ['as' => 'cnewsposts.report' , 'uses' => 'CNewsPostController@reportInappropriate']);
Route::get('/cnewsposts/{id}/comments', ['as' => 'cnewsposts.comments' , 'uses' => 'CNewsPostController@viewComments']);
Route::post('/cnewsposts/{id}/comments', ['as' => 'cnewsposts.addcomment' , 'uses' => 'CNewsPostController@addComment']);
Route::resource('/cnewsposts', 'CNewsPostController');

Route::get('/cgeneralusers/{id}/favourites', ['as' => 'cgeneralusers.favs' , 'uses' => 'CRegisteredUserController@viewFavourites']);
Route::get('/cgeneralusers/{id}/subscription', ['as' => 'cgeneralusers.sub' , 'uses' => 'CRegisteredUserController@viewSubscriptions']);
Route::post('/cgeneralusers/{id}/subscription/{withid}', ['as' => 'cgeneralusers.addsub' , 'uses' => 'CRegisteredUserController@addSubscription']);
Route::delete('/cgeneralusers/{id}/subscription/{withid}', ['as' => 'cgeneralusers.unsub' , 'uses' => 'CRegisteredUserController@removeSubscription']);
Route::resource('/cgeneralusers', 'CRegisteredUserController');

Route::resource('/cnewsimages', 'CNewsImageController');

Route::get('/cgeneralusers/{userid}/pms', ['as' => 'cgeneralusers.viewpminbox' , 'uses' => 'CMessageController@viewPmInbox']);
Route::get('/cgeneralusers/{userid}/pms/{withuserid}', ['as' => 'cgeneralusers.viewpm' , 'uses' => 'CMessageController@viewPm']);
Route::post('/cgeneralusers/{userid}/pms/{withuserid}', ['as' => 'cgeneralusers.sendpm' , 'uses' => 'CMessageController@sendPm']);

Route::get('/cgeneralusers/{userid}/friends', ['as' => 'cgeneralusers.viewfriends' , 'uses' => 'CFriendController@viewFriends']);
Route::post('/cgeneralusers/{userid}/friends/{frdid}', ['as' => 'cgeneralusers.addfriend' , 'uses' => 'CFriendController@addFriend']);
Route::delete('/cgeneralusers/{userid}/friends/{frdid}', ['as' => 'cgeneralusers.removefriend' , 'uses' => 'CFriendController@removeFriend']);


//Route::get('/archived', 'NewsPostController@indexArchive');

Route::get('testAkismet', function() {
	/*
    $Akismet = new Akismet('521e2a5c591e');
    $comment_data = array(
    
    'comment_content'  => 'X YOU ALL',
	);
    $response = $Akismet->checkSpam($comment_data);
    dd($response["spam"]);
    */

    // Create Image Model
			$oldInput = Input::all();
			$imageModelData = array('filename' => '$finalFileName', 'registereduser_mk' => '37', 'newspost_mk' => '1');
			//Input::replace($input);
			$request = Request::create('/cnewsimages', 'POST', $imageModelData);
			$response = Route::dispatch($request);
			$content = $response->getContent();
			$code = $response->getStatusCode();
			$results = json_decode($content);
			Input::replace($oldInput);
});

Route::get('akismet', function() {
	
    $Akismet = new Akismet('521e2a5c591e');

    $comment_data = array(
    'blog'                  => 'http://www.mysitehere.com',
    'user_ip'               => 'x.x.x.x',
    'user_agent'            => $_SERVER['HTTP_USER_AGENT'],
    'comment_type'          => 'comment',
    //'comment_author'        => 'John Doe',
    //'comment_author_email'  => 'john@example.com',
    //'comment_author_url'    => 'http://example.com/johndoe',
   
    'comment_content'  => 'You have won! Call us and give us your credit card number!',
	);
    $response = $Akismet->checkSpam($comment_data);
    dd($response["spam"]);
    
});

Route::get('helloworld', function() {
$searchModel = new NewsPost;
$latitudeSameCount = $searchModel->where('latitude', '=', 22.28468)->count();
dd($latitudeSameCount);
});


/* YouTube */
Route::get('youtube-upload-example/get-access-token', function() {
		$authUrl = Youtube::createAuthUrl();
		return View::make('laravel-youtube::example')->with(compact('authUrl'));
	});

/* note: all routes must be before its relative "resource" routing statement */